version: '3.8'

services:
  # spin up a database
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: turing
      POSTGRES_PASSWORD: turing
      POSTGRES_DB: expenses
    ports:
      - "5432"
    volumes:
      - expenses-db:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - ./server/.env
    environment:
      DB_HOST: postgres
      DB_USER: turing
      DB_PASSWORD: turing
      DB_NAME: expenses
      PORT: 3000
    ports:
      - "3000"
    depends_on:
      - postgres

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        VITE_API_ORIGIN: http://localhost:3001
        VITE_API_PATH: /api/v1/trpc
    environment:
      API_PROXY_PASS: http://server:3000
    ports:
      - "3001:80"
    depends_on:
      - server

volumes:
  expenses-db:
